elasticsearch:
  image: jbrinley/elasticsearch:1.3
  volumes_from:
    - elasticsearchdata
  ports:
    - "9200:9200"
memcached:
  image: memcached:1.4
  ports:
    - "11211:11211"
mysql:
  image: mysql:5.5
  volumes_from:
    - mysqldata
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password