memcached:
  image: memcached:1.4
  ports:
    - "11211"
php56:
  image: jbrinley/php:5.6-fpm
  volumes:
    - ~/projects:/srv/www
  dns:
    - 10.254.254.254
    - 8.8.8.8
  links:
    - memcached
  external_links:
    - core_mysql_1:mysql
    - core_elasticsearch_1:elasticsearch
php55:
  image: jbrinley/php:5.5-fpm
  volumes:
    - ~/projects:/srv/www
  dns:
    - 10.254.254.254
    - 8.8.8.8
  links:
    - memcached
  external_links:
    - core_mysql_1:mysql
    - core_elasticsearch_1:elasticsearch
php54:
  image: jbrinley/php:5.4-fpm
  volumes:
    - ~/projects:/srv/www
  dns:
    - 10.254.254.254
    - 8.8.8.8
  links:
    - memcached
  external_links:
    - core_mysql_1:mysql
    - core_elasticsearch_1:elasticsearch
php53:
  image: jbrinley/php:5.3-fpm
  volumes:
    - ~/projects:/srv/www
  dns:
    - 10.254.254.254
    - 8.8.8.8
  links:
    - memcached
  external_links:
    - core_mysql_1:mysql
    - core_elasticsearch_1:elasticsearch
php52:
  image: jbrinley/php:5.2-fpm
  volumes:
    - ~/projects:/srv/www
  dns:
    - 10.254.254.254
    - 8.8.8.8
  links:
    - memcached
  external_links:
    - core_mysql_1:mysql
    - core_elasticsearch_1:elasticsearch
nginx:
  image: nginx:latest
  ports:
    - "80:80"
  volumes:
    - ../../shared-config/nginx:/etc/nginx:ro
    - nginx/php/php-upstream.conf:/etc/nginx/php/php-upstream.conf:ro
    - ~/projects:/srv/www:ro
  links:
    - php55
    - php54
    - php53
    - php52
