web:
  image: jbrinley/php:5.4-apache
  ports:
    - "80:80"
    - "9090:9090"
  volumes:
    - ../../shared-config/apache/sites-enabled:/etc/apache2/sites-enabled/:ro
    - ../../shared-config/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
    - /Users/jbrinley/projects:/srv/www
  external_links:
    - web_mysql_1:mysql
    - web_memcached_1:memcached
