memcached:
  image: memcached:1.4
  ports:
    - "11211"
web:
  image: jbrinley/php:5.5-apache
  environment:
    - VIRTUAL_HOST=sls.tribe
  dns:
    - 10.254.254.254
    - 8.8.8.8
  volumes:
    - apache/sites-enabled:/etc/apache2/sites-enabled/
    - php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ~/projects/tribe/sls:/srv/www/default/application
  links:
    - memcached
  external_links:
    - core_mysql_1:mysql
