memcached:
  image: memcached:1.4
  ports:
    - "11211"
php:
  image: jbrinley/php:5.5-fpm
  volumes:
    - ~/projects:/srv/www
    - ../../shared-config/php/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
  dns:
    - 10.254.254.254
    - 8.8.8.8
  links:
    - memcached
  external_links:
    - core_mysql_1:mysql
    - core_elasticsearch_1:elasticsearch
nginx:
  image: nginx:latest
  environment:
    - VIRTUAL_HOST=*.gentoo,*.tribe
  volumes:
    - ../../shared-config/nginx:/etc/nginx:ro
    - ~/projects:/srv/www:ro
  links:
    - php
