elasticsearch:
  image: jbrinley/elasticsearch:1.3
  volumes_from:
    - elasticsearchdata
  ports:
    - "9200:9200"
mysql:
  image: mysql:5.5
  volumes_from:
    - mysqldata
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=password
proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    - nginx/proxy_settings.conf:/etc/nginx/conf.d/proxy_settings.conf:ro
    - /var/run/docker.sock:/tmp/docker.sock